'use client'

import { Inter } from 'next/font/google'
import {ScriptProps} from "next/script";
import { createCache, extractStyle, StyleProvider } from '@ant-design/cssinjs';
import './globals.css'
import Link from "next/link";
import {Menu} from "antd";

const inter = Inter({ subsets: ['latin'] })
const cache = createCache();
const styleText = extractStyle(cache);

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  styleText: styleText
}

export default function RootLayout(props: ScriptProps){
  return (
    <html lang="zh-CN">
      <body className={inter.className}>
        <StyleProvider cache={cache}>
          {props.children}
        </StyleProvider>
      </body>
    </html>
  )
}
